Start using main config file to drive options like include_file_patterns

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -10,6 +10,10 @@ inputs:
   MCD_DEFAULT_API_TOKEN:
     description: '[Secret] MonteCarlo API token'
     required: true
+  USE_CONFIG_YML:
+    description: 'Use options like include_file_patterns in montecarlo.yml to drive dry-run/apply'
+    required: false
+    default: 'false'
   MONITORS_FOLDER:
     description: 'Top level folder containing monitors, within which is folders for each namespace'
     default: 'monitors'
@@ -42,20 +46,24 @@ runs:
         MONITORS_FOLDER: ${{ inputs.MONITORS_FOLDER }}
         DRY_RUN: ${{ inputs.DRY_RUN }}
       run: |
-        for dir in $MONITORS_FOLDER/* ; do
-        if $DRY_RUN
-        then
-          echo "Dry run of monitors in $dir"
-          pushd ./$dir
-          montecarlo monitors apply --dry-run
-          popd
-        else
+        FLAG="--dry-run"
+        if [ "$DRY_RUN" = false ]; then
+          FLAG="--auto-yes"
           echo "Applying monitors in $dir"
-          pushd ./$dir
-          montecarlo monitors apply --auto-yes
-          popd
+        else
+          echo "Dry run of monitors in $dir"
         fi
-        done || {
-          echo "Error applying monitors in $dir"
-          exit 1
-        }
+        
+        if [ "$USE_CONFIG_YML" = true ]; then
+          montecarlo monitors apply $FLAG
+        else
+          for dir in $MONITORS_FOLDER/* ; do
+            pushd ./$dir
+            montecarlo monitors apply $FLAG
+            popd
+          done || {
+            echo "Error applying monitors in $dir"
+            exit 1
+          }
+        fi
+  
